version: '3.9'

networks:
  my_docker_network:

services:
  mysql:
    # use e.g. MySQL Shell (https://dev.mysql.com/doc/mysql-shell/8.0/en/):
    #   mysqlsh -u root -h 127.0.0.1
    #   \sql (Backslash in macOS: Shift+Option+7)
    #   use <databasename>;
    #   show tables;
    #   select * from <table>;
    #   \quit
    # docker commands
    #  start containers
    #   docker compose up
    #  remove all stopped containers
    #   docker rm $(docker ps --filter status=exited -q)
    #  remove all images not in use
    #   docker image prune -a
    #  remove all containers not in use
    #   docker container prune
    image: mariadb:11.7.2
    #    platform: linux/x86_64
    #    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - my_docker_network