networks:
  my_docker_network:

services:
  mysql:
    # use e.g. MySQL Shell (https://dev.mysql.com/doc/mysql-shell/8.3/en/), install in macOS with brew install --cask mysql-shell:
    #   mysqlsh -u root -h 127.0.0.1
    #   \sql (macOS: Option+Shift+7 for '\' character)
    #   use <databasename>
    #   show tables;
    #   select * from <table>;
    # docker commands
    #  start containers
    #   docker compose up
    #  remove all stopped containers
    #   docker rm $(docker ps --filter status=exited -q)
    #  remove all images not in use
    #   docker image prune -a
    #  remove all containers not in use
    #   docker container prune
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default_authentication_plugin=caching_sha2_password
    ports:
      - "3306:3306"
    networks:
      - my_docker_network

